### ISSUE TITLE
Add Chromebook support

### ISSUE THREAD

**Issue by johnspurlock** [Yubico/yubioath-android#60] opened 2017-06-20 16:54 UTC
I have a Chromebook Plus with Android app support.  The authenticator app (version 1.2.1) installs and launches on the device, but does not respond to taps on the yubikey neo button.

The yubikey is connected via usb-a to usb-c, and I've validated that Android apps can see the "ccccc..." input when tapping the button.  The Chromebook itself does not have NFC at all, so will need to use the recently added usb support instead, and it only has usb-c ports.

Any tips / patches to get this working would be much appreciated!

**Comment by dainnilsson** [comment] 2017-07-18 19:46
I don't have any experience in running Android apps on ChromeOS, but some quick Googling led me to this: https://developer.android.com/topic/arc/manifest.html
It looks like a lot of features are unavailable when running on ChromeOS. Specifically the `android.hardware.usb.host` hardware feature is listed as unsupported, which is required for this app. Closing the issue for now. Feel free to re-open if USB support for Android apps on ChromeOS changes!

**Comment by johnspurlock** [comment] 2017-09-23 00:35
What are your thoughts on the feasibility of a web app version, using [WebUSB](http://caniuse.com/#feat=webusb)?  Which the latest ChromeOS supports.

**Comment by dainnilsson** [comment] 2017-09-25 09:23
I don't have any experience with the WebUSB APIs either, but it might be feasible. Clearly it would require a lot of effort to do.

**Comment by smiller171** [comment] 2018-04-30 19:57
Might it be easier to use the Chrome USB API than WebUSB? https://developer.chrome.com/apps/app_usb

**Comment by ZaeGitHub** [comment] 2019-01-06 05:48
It looks like Chrome OS has added USB Host support, but via a flag:
https://chromium-review.googlesource.com/c/chromium/src/+/854990

I have confirmed this is in the Chrome OS Stable channel (71) currently and can be enabled.

**Comment by smiller171** [comment] 2019-01-07 15:55
> It looks like Chrome OS has added USB Host support, but via a flag:
> https://chromium-review.googlesource.com/c/chromium/src/+/854990
> 
> I have confirmed this is in the Chrome OS Stable channel (71) currently and can be enabled.

Have you checked if this works for the Yubico Authenticator app?

**Comment by ZaeGitHub** [comment] 2019-01-07 16:03
> > It looks like Chrome OS has added USB Host support, but via a flag:
> > https://chromium-review.googlesource.com/c/chromium/src/+/854990
> > I have confirmed this is in the Chrome OS Stable channel (71) currently and can be enabled.
> 
> Have you checked if this works for the Yubico Authenticator app?

Unfortunately, I cannot test this. I do not have my Pixelbook in Developer Mode to sideload APKs and the Yubico Authenticator app is marked as "Not compatible" in the Play Store for the Pixelbook so I cannot install it from there.

**Comment by smiller171** [comment] 2019-01-09 15:21
> That's an interesting update. What are the steps to enable this flag?
> 
> I checked the store listing, and the reason the app won't install on a Pixelbook at the moment is due to the android.hardware.camera requirement, which also doesn't seem to be supported on ChromeOS. Technically the app could function without it, by using manual credential entry, so we might be able to mark that dependency as optional. I currently don't have a Pixelbook (or other ChromeOS device) to test with myself, unfortunately.

You could also let devices without the camera be read-only. I'd definitely make that optional.

If you were to release a beta version to the Play store with that marked as optional it could be tested without having to enable dev mode. I have a Pixelbook that I'd be happy to test on (currently beta channel) though I'd prefer not needing to enable dev mode because of the annoyances that comes with.

**Comment by smiller171** [comment] 2019-01-09 15:21
Oh...dev mode may not be needed though because of the Android Studio integration they rolled out?

**Comment by ZaeGitHub** [comment] 2019-01-10 13:16
> That's an interesting update. What are the steps to enable this flag?
> 
> I checked the store listing, and the reason the app won't install on a Pixelbook at the moment is due to the android.hardware.camera requirement, which also doesn't seem to be supported on ChromeOS. Technically the app could function without it, by using manual credential entry, so we might be able to mark that dependency as optional. I currently don't have a Pixelbook (or other ChromeOS device) to test with myself, unfortunately.

1. Open Chrome and go to chrome://flags/#arc-usb-host
2. Click the dropdown and select "Enabled."
3. Restart Chrome OS

I also have a Pixelbook that I am happy to test on. I am on the Stable channel. Unfortunately, I do not see the beta on the Play Store. Can you please provide a link?

**Comment by dainnilsson** [comment] 2019-01-10 13:21
I'm not sure of how it works on ChromeOS, but for Android in the Play store listing there's a button to opt in to the beta channel for each specific app (if the app offers it). You scroll down a bit and there's a "Become a beta tester" section.

**Comment by dainnilsson** [comment] 2019-01-10 13:35
Well, at least the app starts, I guess that's something. To dig into this further I think it will be required to run in developer mode and run the app with debug output. I'll see about getting a hold of a Pixelbook to do some in-house experimentation with. Thanks for trying it out!

**Comment by smiller171** [comment] 2019-01-10 15:49
@dainnilsson You should be able to use any Chromebook with Android App support if you have something other than a Pixelbook around.

**Comment by scarolan** [comment] 2019-04-06 16:34
USB support is here.  @dainnilsson can we consider re-opening this issue?  

https://www.aboutchromebooks.com/news/chrome-os-72-dev-channel-usb-sd-card-support-project-crostini-chromebooks-android-9-pie/

It's appears to still be in dev but at least we could try and see if it works now.

**Comment by smiller171** [comment] 2019-04-08 13:46
@scarolan Unfortunately that only brings support for USB mass storage by mounting the volume in the container. [here](https://bugs.chromium.org/p/chromium/issues/detail?id=831850&q=Proj%3DContainers%20&sort=-modified&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) is the issue for tracking full USB support in Linux containers, which would likely also bring the feature to Android apps.

**Comment by dainnilsson** [comment] 2019-04-08 13:53
I tried running this on a Pixelbook a while back (with chrome://flags/#arc-usb-host enabled). The app runs fine, but there is absolutely no reaction when a YubiKey is plugged in. Nothing in the ADB logs or anything. If anyone has anything more insightful, or suggestions on what to try to get it to do, well anything, please let me know.

**Comment by smiller171** [comment] 2019-04-08 14:25
@dainnilsson Yeah now that I look I think that's a legacy flag since Android apps on ChromeOS no longer use ARC. I think we'll still need to wait for full USB support, or work on a Chrome app.

How simple is the USB interface with the Yubikey? It may be worth hacking around with the ChromeOS [USB API](https://developer.chrome.com/apps/usb)

**Comment by scarolan** [comment] 2019-07-28 19:37
Hello all, has anyone had a chance to test the Yubico Authenticator with Chromebook?

**Comment by dragon788** [comment] 2020-02-28 02:11
It sounds like WebUSB may be a no-go due to security concerns of sites directly accessing the hardware and bypassing the U2F/HID interface to snoop things. https://github.com/Yubico/yubioath-desktop/issues/333#issuecomment-547003991

**Comment by Elliander** [comment] 2021-04-06 13:08
I find it extremely annoying that despite the fact that Android apps running on Chromebook are capable of accessing the USB and have been [since 2018](https://www.xda-developers.com/chrome-os-android-apps-usb-drive/) - which I have personally used - the developers of Yubico don't know this and just close issues relating to use on a Chromebook without even looking at it.

You shouldn't advertise Android support if you are going to choose not to support an entire class of Android devices.

**Comment by dainnilsson** [comment] 2021-04-06 13:21
This issue is closed as we (both Yubico developers and others in this thread), have not been able to make use of any relevant USB or NFC support on Chrome OS, despite claims that this "should work". As can be seen in this thread, we have explored the available APIs, and we have yet to see any evidence that they do actually work for the purpose we need them to. This is very different from accessing a USB thumbdrive for storage.

Please don't see the fact that this issue is closed to mean that this will never work, or that we will never implement it. See it more as this isn't something we know how to make work, as of now. If anything new comes to light that unblocks this we'll be happy to re-open.

Regarding the Titan Security key, this is a FIDO-only device. YubiKeys also work just as well on ChromeOS for the FIDO protocols. Yubico Authenticator uses an entirely different protocol and USB interface.

**Comment by smiller171** [comment] 2021-04-06 14:18
@dainnilsson might it make sense to have an ongoing issue left open for researching options for Chromebook support, so there can be a single place for these discussions to move forward rather than more issues opening all the time?

**Comment by dainnilsson** [comment] 2021-04-06 14:25
> @dainnilsson might it make sense to have an ongoing issue left open for researching options for Chromebook support, so there can be a single place for these discussions to move forward rather than more issues opening all the time?

Not a bad idea. We haven't been very diligent about using labels for issues, but having one for issues that are `blocked` seems to make sense to me, and keep them open for discoverability. I'll make the change!

**Comment by Wilford888** [comment] 2021-08-14 19:17
> 
> 
> I find it extremely annoying that despite the fact that Android apps running on Chromebook are capable of accessing the USB and have been [since 2018](https://www.xda-developers.com/chrome-os-android-apps-usb-drive/) - which I have personally used - the developers of Yubico don't know this and just close issues relating to use on a Chromebook without even looking at it.
> 
> `#arc-usb-host`
> 
> You shouldn't advertise Android support if you are going to choose not to support an entire class of Android devices. and if you find the limitations of Android difficult to get around on Chromebook you should implement native support.
> 
> Your competition - Google's Titan Security Key - [is fully supported on Chromebooks now.](https://www.aboutchromebooks.com/news/chromebooks-gain-native-support-for-2fa-and-faster-web-sign-ins-with-chrome-os-88/) So why can't you support it?

Yes.  This is lame, and requests addressed to support only produce lame replies.

**Comment by smiller171** [comment] 2021-11-19 18:21
The titan security key is only a U2F key. U2F functionality isn't the problem. The problem is interacting more directly with the USB device to interact with the custom TOTP api Yubico implemented.

**Comment by AdamVe** [comment] 2022-11-16 10:14
The development of the app moved to https://github.com/Yubico/yubioath-flutter and we have released a new version of the app. Thank you for the suggestion, we will consider it for development in the new version. Please report any new issues in the new repository.

**Closed by AdamVe** 2022-11-16 10:14 UTC
Labels: blocked
