### ISSUE TITLE
Samsung Galaxy S5 NFC Service Crashes

### ISSUE THREAD

**Issue by aganser** [Yubico/yubioath-android#9] opened 2014-12-17 10:45 UTC
See http://forum.yubico.com/viewtopic.php?t=1646

I can read the NEO once with the S5 without problem, trying to read it once again just seams to hang the nfc processes on the phone. If i disable NFC on the phone and enable it again I'm able to read the NEO once more. When it's not possible to read the NEO it's not possible to read any other NFC tags. Same scenario works with out problem on S3,S4,Z3 and so on.

Background:
Model: SM-G900F
Android 4.4.2
Kernel 3.4.0-2089850
Baseband: G900FXXU1ANG2

Symptoms:
After one read(successful OR failed), it will not read again

Workarounds:
- wait at least a minute then try again(does not always work, 50/50...)
- disable/enable NFC
- lock/unlock the phone

Comments:
On the first attempt, the S5 seems to be able to successfully read the Neo only about 50% of the time, sometimes I get error "Unfortunately, NFC Service has stopped", but most times it just simply will not read again until doing one of the above 'workarounds'. After a failed read, if I immediately exit the Yubico Authenticator then re-load it, I get message "NFC is disabled" but when I check, it is actually enabled. So it seems that the NFC service is crashing for some reason. Note: I have never seen "NFC is disabled" message after a successful read, but it still will not read again until doing one of the workarounds above.

Additional Info:
Adb logcat says when scanning Neo first time:

D/NativeNfcTag(11676): connectWithStatus- technology =3
D/NativeNfcTag(11676): Connect to a tech with a different handle
D/NativeNfcTag(11676): Starting background presence check
D/NfcDispatcher(11676): tryStartActivity. Send intent.
V/ApplicationPolicy( 807): isApplicationStateBlocked userId 0 pkgname com.android.nfc
D/NfcService(11676): tag value : none
V/SmartFaceService - 3rd party pause( 807): onReceive [android.intent.action.ACTIVITY_STATE/com.android.nfc/create]
V/SmartFaceService - 3rd party pause( 807): onReceive [android.intent.action.ACTIVITY_STATE/com.android.nfc/pause]
D/NativeNfcTag(11676): Tag lost, restarting polling loop
D/NativeNfcTag(11676): Stopping background presence check
E/NfcNfa (11676): nfa_dm_act_deactivate (): invalid protocol, mode or state

When trying to scan ANY tag after this, nothing happens.

The 2 last lines look not to good, in my eyes at least... Doing the same on S3 doesn't provide as much detail

D/NfcDispatcher( 2940): tryStartActivity. Send intent.
D/NfcService( 2940): tag value : none
D/NativeNfcTag( 2940): Tag lost, restarting polling loop

But on S3 it works all the time.

**Comment by public** [comment] 2015-01-22 09:23
FWIW I also get this behaviour. My S5 is the same version and model variant as @aganser. I expect this is a bug in the Samsung NFC implementation though :(

**Comment by getresults** [comment] 2015-03-30 07:53
I also get this issue. I submitted a support request to yubico but no response so far.

**Comment by dainnilsson** [comment] 2015-03-30 08:12
We've gotten several of these reports regarding the S5. As far as we can tell, it's an issue with the NFC stack on the phone itself. We officially support Nexus devices and do all our testing and development on those, thus we have no possibility of reproducing this. That said, if any of you are using a different application on the S5 that uses the IsoDep (http://developer.android.com/reference/android/nfc/tech/IsoDep.html) APIs that doesn't cause these kind of crashes, and is open source, point me to it and I'll see if they're doing anything differently. It's possible that there is some workaround which would cause S5's to behave better.

**Comment by MichaelKling** [comment] 2015-10-07 07:52
I got the same issue, same model but using android 5.

Can you name such application's so I can test it?

**Comment by MichaelKling** [comment] 2015-10-07 13:54
Alright i created a simple gradle project in android studio in order to test it (see https://github.com/MichaelKling/MyApplication-YubikeyTest/tree/master )

The issue appears without using the IsoDep Library at all (Not using IsoDep.get(tag)). It hast to be an issue in the underlying system and i'm afraid it's not fixable within an app.
In order to ensure "connectivity" i opened the phones case and hold the Yubikey NEO 0.5cm next to the NFC antenna.

I was really looking for that feature and it's sad that it doesn't work on (some?) Galaxy S5 devices.
I suggest taking it out of this list: http://forum.yubico.com/viewtopic.php?f=26&t=1302 - as the state of "working" isn't satisfying at all. 

If there is anything else I can do to help you fixing that issue please let me know. Maybe it's possible to fix it with a custom rom.

**Comment by dainnilsson** [comment] 2015-10-07 14:16
Thanks for doing some testing. It's unfortunate that there likely isn't anything we can do about it. We've updated the forum topic to at least make people aware of the issue.

**Comment by Franzaine** [comment] 2015-10-14 11:24
I think this could be solved by Nordpol ( https://github.com/fidesmo/nordpol ). I'll take a look soon!

**Comment by Franzaine** [comment] 2015-10-27 12:30
Together with @petter-fidesmo I have put together a pull request that should solve this specific issue. We had the same issue in [the Fidesmo app](https://play.google.com/store/apps/details?id=com.fidesmo.sec.android&hl=en) and put the solution into [the Nordpol library](https://github.com/fidesmo/nordpol). I don't have an S5 around and therefore need some help testing it. @MichaelKling @getresults @aganser @public if one of you can compile and run the app on your device? This is the PR that needs testing: https://github.com/Yubico/yubioath-android/pull/23
If you don't want to compile yourself but still are interested in testing, here is an APK ready to install: https://drive.google.com/file/d/0B8Fc6Qd_aBaXRzFCXzNWa21EcDQ/view?usp=sharing

**Comment by MichaelKling** [comment] 2015-10-27 19:25
I've the yubikey, the phone, the laptop but i forgot the usb cable... had to test with your precompiled apk file and could only visually check for the "Empty credentials list" Toast.
It lools like this really solved the issue - the toast came almost every time with cover and all the time without cover (so very likely an issue of signal absorption of my cover).

I will get a cable for tomorrow to check it with adb and mabe even trying to upgrade my test application.

**Comment by Franzaine** [comment] 2015-10-28 10:38
@MichaelKling Great! Looking forward to your conclusions :)

**Comment by MichaelKling** [comment] 2015-10-28 21:55
Alright i got the adb output.
The shortversion prefiltered with yubioath|nfc: https://gist.github.com/MichaelKling/7710fefd3c896af8af05
And the full version: https://gist.github.com/MichaelKling/4d3e7a69583f360e3f5d

So what are we looking at: 
I started holding the yubikey at my devices back, using the devices cover at 10-28 22:14:35.418 - everything seems functional and i repeat the process several times until i get at 10-28 22:15:02.848  "connection failed - status 3".
From that point on i can not read the yubikey anymore. 

I take the phone out of my cover, go in the lock screen and unlock it again - then try again reading the yubikey.
At that point we even get the message 10-28 22:17:41.138 I/ServiceManager: service 'nfc' died.
It seems that the nfc library is loaded again and everything works fine again, until at one point 10-28 22:18:39.508 D/NativeNfcTag: Connect Failed - status = 3, it stops working again.

It is possible that it fails when the yubikey isn't positioned correctly and it cant be accessed reliable. That's why it worked much longer without the cover - until i was a little bit sloppy and didnt put it exactly on top of the nfc antenna.

I locked the screen and then entered again into android and tried a little bit more until 
10-28 22:19:31.248 D/NativeNfcTag and then something really strange happened.
Even though i could restart the nfc lib (by locking the screen and entering again) i got exceptions including backtraces for every yubikey reading. The app worked fine on the first exceptions but when the E/yubioath IOException appeared it showed a Toast "Error in Yubikey communication!" 

You can see them here:
10-28 22:20:20.128 8029-8029/com.yubico.yubioath E/NFC: android.os.DeadObjectException
10-28 22:20:20.128 8029-8029/com.yubico.yubioath E/NFC: NFC service dead - attempting to recover
10-28 22:20:20.128 8029-8029/com.yubico.yubioath E/NFC: android.os.DeadObjectException
10-28 22:20:27.808 8029-8029/com.yubico.yubioath E/NFC: NFC service dead
10-28 22:20:27.808 8029-8029/com.yubico.yubioath E/NFC: android.os.DeadObjectException
10-28 22:20:27.818 8029-8029/com.yubico.yubioath E/yubioath: IOException in handler
10-28 22:20:27.818 8029-8029/com.yubico.yubioath E/yubioath: java.io.IOException: NFC service died

I tried several more times, carefully placing the yubikey directly on top of the nfc antenna and was able to get a successful read 31 times in a row. It is a huge improvement 
1. i could read many more then 1 time until it crashed
2. i could reliably restart the nfc service by closing the app, locking the screen and unlock the screen

**Comment by Franzaine** [comment] 2015-10-29 13:16
Thanks for testing @MichaelKling ! We did also see some spontaneous NFC crashes when we tested on the S5. In general it seems their NFC stack is a bit buggy. On the other hand, for us, after the fixes it went from unusable to usable ([issue in Nordpol](https://github.com/fidesmo/nordpol/issues/31))
I'd say the improvement that you spoke of already makes the app far more usable with the S5! I'll send it on for review!
Thanks again!

**Closed** 2015-11-13 11:11 UTC

**Comment by petter-fidesmo** [comment] 2015-12-08 14:27
@MichaelKling We are working on solving issue #29 and have something that works as well as pre 1.0.3 versions for the S6 there, but I am uncertain how well this will work with the S5? The workaround for the S5 is not related to the workarounds that we have disabled for the S6 to work, so 
in theory it should work with the S5, but we have no earlier experience of this combination.

Would it be possible for you to give it a try?
http://nordpol.fidesmo.com.s3-website-eu-west-1.amazonaws.com/yubioath.apk

Thanks!

**Comment by msnorm** [comment] 2015-12-17 08:06
yea same for me, the NFC has not worked properly since I bought the yubikey a few weeks ago :( I would have just bought the y4 if I knew it wouldn't work =,=

**Comment by MichaelKling** [comment] 2016-03-08 15:08
@petter-fidesmo sorry for responding that late - was pretty bussy.

i tested the version you linked and have similar results to what i got in octobre.

I can do multiple reads (until i get sloppy) and am able to reliably restart when i lock the phone and unlock it again.

My device currently (i think there where some updates since the last test):
Model: SM-G900F
Android 5.0
Kernel 3.4.0-5954332
Baseband: G900FXXU1POI2
